name: CD

on:
  pull_request:
    branches: main
    types: closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  setup:
    name: Set up
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: Install tools
      uses: aquaproj/aqua-installer@v3.1.0
      with:
        aqua_version: v2.40.0      
    
    - name: Get changed working directory
      uses: suzuki-shunsuke/tfaction/list-targets@v1.14.0
      id: list-targets

  apply:
    name: Apply (${{ matrix.target.target }})
    needs: setup    
    if: join(fromJSON(needs.setup.outputs.targets), '') != ''    
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
      TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
      TFACTION_IS_APPLY: true
    strategy:
      fail-fast: true
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Install tools
        uses: aquaproj/aqua-installer@v3.1.0
        with:
          aqua_version: v2.40.0

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private_key: ${{ secrets.TFACTION_GITHUB_APP_PRIVATE_KEY }}

      - name: Set up
        uses: suzuki-shunsuke/tfaction/setup@v1.14.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Apply
        uses: suzuki-shunsuke/tfaction/apply@v1.14.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Follow up PR
        uses: suzuki-shunsuke/tfaction/create-follow-up-pr@v1.14.0
        if: failure()
        with:
          github_token: ${{ steps.generate_token.outputs.token }}